package com.venenatis.game.task;

public enum TaskIdentifier {
	CURRENT_ACTION,
	TELEPORTING,
	SPECIAL_RESTORE,
	COMBAT,
	SEQUENTIAL_MINIGAME,
	LOOSE_TARGET,
	FISHING,
	WOODCUTTING,
	MINING,
	COOKING,
	MINIGAME,
	OBJECT_REPLACEMENT;
}